=== Abhishek2147203/Train-freight-management/CIA1.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="Company">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Employee" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="id" type="xs:byte"></xs:element>
              <xs:element name="Name" type="xs:string"></xs:element>
              <xs:element name="Age" type="xs:string"></xs:element>
              <xs:element name="Salary" type="MySal"></xs:element>
              <xs:element name="email" type="xs:string"></xs:element>
              <xs:element name="MobNum" type="xs:long"></xs:element>
              <xs:element name="Designation" type="xs:string"></xs:element>
              <xs:element name="Promotion" type="xs:string"></xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:simpleType name="MySal">
 <xs:restriction base="xs:integer">
 <xs:minInclusive value="50000"></xs:minInclusive>
 <xs:maxInclusive value="200000"></xs:maxInclusive>
 </xs:restriction>
 </xs:simpleType>
</xs:schema>

=== Abhishek2147203/Train-freight-management/CIA1.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="CIA11.xsl"?>
<Company xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="CIA1.xsd">
   <Employee>
      <id>101</id>
      <Name>Anand</Name>
      <Age>50</Age>
      <Salary>100000</Salary>
      <email>anand@gmail.com</email>
      <MobNum>6299877413</MobNum>
      <Designation>Project Manager</Designation>
      <Promotion>Associative Project Manager</Promotion>
   </Employee>
   <Employee>
      <id>102</id>
      <Name>Abhishek</Name>
      <Age>57</Age>
      <Salary>200000</Salary>
      <email>abhishek@gmail.com</email>
      <MobNum>9162126098</MobNum>
      <Designation>Project Manager</Designation>
      <Promotion>Associative Project Manager</Promotion>
   </Employee>
   <Employee>
      <id>103</id>
      <Name>Saurabh</Name>
      <Age>47</Age>
      <Salary>170000</Salary>
      <email>saurabh@gmail.com</email>
      <MobNum>9934654773</MobNum>
      <Designation>Testing</Designation>
      <Promotion>Team Leader</Promotion>
   </Employee>
   <Employee>
      <id>104</id>
      <Name>Utkarsh Razz</Name>
      <Age>42</Age>
      <Salary>190000</Salary>
      <email>utkarsh@gmail.com</email>
      <MobNum>9955019735</MobNum>
      <Designation>Developer</Designation>
      <Promotion>Team Leader</Promotion>
   </Employee>
   <Employee>
      <id>105</id>
      <Name>Sonu</Name>
      <Age>30</Age>
      <Salary>150000</Salary>
      <email>sonu@gmail.com</email>
      <MobNum>8210687720</MobNum>
      <Designation>Assitant Developer</Designation>
      <Promotion>Developer</Promotion>
   </Employee>
   <Employee>
    <id>106</id>
    <Name>Satyam</Name>
    <Age>28</Age>
    <Salary>50000</Salary>
    <email>satyam@gmail.com</email>
    <MobNum>8210685576</MobNum>
    <Designation>Assitant Developer</Designation>
    <Promotion>N/A</Promotion>
 </Employee>
 <Employee>
    <id>107</id>
    <Name>Satyam</Name>
    <Age>25</Age>
    <Salary>50000</Salary>
    <email>satyam@gmail.com</email>
    <MobNum>8210685576</MobNum>
    <Designation>Assitant Developer</Designation>
    <Promotion>N/A</Promotion>
 </Employee>
 <Employee>
    <id>108</id>
    <Name>Aayushi</Name>
    <Age>23</Age>
    <Salary>52000</Salary>
    <email>ayushi@gmail.com</email>
    <MobNum>9091068557</MobNum>
    <Designation>Data Analysit</Designation>
    <Promotion>N/A</Promotion>
 </Employee>
 <Employee>
    <id>109</id>
    <Name>Munna</Name>
    <Age>22</Age>
    <Salary>60000</Salary>
    <email>munna@gmail.com</email>
    <MobNum>8210685576</MobNum>
    <Designation>Assitant Developer</Designation>
    <Promotion>Developer</Promotion>
 </Employee>
</Company>
