=== Abhishek2147203/Train-freight-management/Ptest.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="FIOS">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="Payment" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:byte" name="pid"/>
              <xs:element type="xs:string" name="pstatus"/>
              <xs:element type="xs:int" name="amt"/>
              <xs:element type="xs:string" name="pmethod"/>
              <xs:element type="xs:byte" name="bid"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== Abhishek2147203/Train-freight-management/Payment.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="Payment.xsl"?>
<FIOS xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="Ptest.xsd">
   <Payment>
      <pid>001</pid>
      <pstatus>SUCCESS</pstatus>
      <amt>1000</amt>
      <pmethod>UPI</pmethod>
      <bid>101</bid>
   </Payment>
   <Payment>
      <pid>002</pid>
      <pstatus>SUCESS</pstatus>
      <amt>5000</amt>
      <pmethod />
      <bid>101</bid>
   </Payment>
   <Payment>
      <pid>002</pid>
      <pstatus>SUCCESS</pstatus>
      <amt>6000</amt>
      <pmethod>GooglePay</pmethod>
      <bid>102</bid>
   </Payment>
   <Payment>
      <pid>003</pid>
      <pstatus>Failure</pstatus>
      <amt>7000</amt>
      <pmethod>Card</pmethod>
      <bid>103</bid>
   </Payment>
   <Payment>
      <pid>004</pid>
      <pstatus>SUCCESS</pstatus>
      <amt>150000</amt>
      <pmethod>PayPhone</pmethod>
      <bid>103</bid>
   </Payment>
</FIOS>
