=== Abhishek2147203/Train-freight-management/test.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="FIOS">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" name="user">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="id" type="ID" use="required"/>
              <xs:element name="Name" type="xs:string" />
              <xs:element name="Age"  type="MyAge" />
              <xs:element name="email" type="xs:string" />
              <xs:element name="phone" type="MyPhone" />
            </xs:sequence>
          </xs:complexType>
        </xs:element>
         <xs:simpleType name="MyAge">
         <xs:restriction base="xs:integer">
         <xs:minInclusive value="18"></xs:minInclusive>
         <xs:maxInclusive value="75"></xs:maxInclusive>
         </xs:restriction>
         </xs:simpleType>
         <xs:simpleType name="MyPhone">
         <xs:restriction base="xs:integer">
         <xs:totalDigits value="10"/>
         </xs:restriction>
          <xs:simpleType name="MyPhone">
         <xs:restriction base="xs:integer">
          <xs:pattern value="\d{10}"/>
         </xs:restriction>
         </xs:simpleType>
        </xs:schema>

=== Abhishek2147203/Train-freight-management/My.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="User.xsl"?>
<FIOS xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="test.xsd">
  <user>
    <id>001</id>
    <Name>Anand</Name>
    <Age>18></Age>
    <email>anand@gmail.com</email>
    <phone>9162126098</phone>
  </user>
   <user>
    <id>002</id>
    <Name>Rahul</Name>
    <Age>18></Age>
    <email>rahul@gmail.com</email>
    <phone>9162126098</phone>
  </user>
   <user>
    <id>003</id>
    <Name>Aryan</Name>
    <Age>18></Age>
    <email>aryan@gmail.com</email>
    <phone>9162126098</phone>
  </user>
   <user>
    <id>004</id>
    <Name>Abhishek</Name>
    <Age>18></Age>
    <email>abhishek@gmail.com</email>
    <phone>9162126098</phone>
  </user>
  <user>
    <id>005</id>
    <Name>Amit</Name>
    <Age>18></Age>
    <email>amit@gmail.com</email>
    <phone>9162126098</phone>
  </user>
  <user>
    <id>006</id>
    <Name>Rana</Name>
    <Age>18></Age>
    <email>rana@gmail.com</email>
    <phone>9934654773</phone>
  </user>
  <user>
    <id>007</id>
    <Name>Srishty</Name>
    <Age>18></Age>
    <email>srishty@gmail.com</email>
    <phone>6204617238</phone>
  </user>
  <user>
    <id>008</id>
    <Name>Anil</Name>
    <Age>18></Age>
    <email>anil@gmail.com</email>
    <phone>6299877413</phone>
  </user>
</FIOS>
